server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
          filters:
            - RewritePath=/inventory-service/(?<path>.*), /$\{path}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics-service/**
          filters:
            - RewritePath=/analytics-service/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Inventory Service
        url: /inventory-service/v3/api-docs
      - name: Order Service
        url: /order-service/v3/api-docs
      - name: Analytics Service
        url: /analytics-service/v3/api-docs
