server:
  port: 8082

spring:
  application:
    name: analytics-service
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: analytics-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: "com.oussama.analyticsservice.dto"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
